### ISSUE TITLE
What is actual license for ZK opensource spreadsheet component?

### ISSUE THREAD

**Issue by Hubbitus** [zkoss/zkspreadsheet#109]
Hello.

On page https://www.zkoss.org/license stated ZK CE is LGPL (free for open source and proprietary use). Does it cover ZK spreadsheet?
In some pages I found mention of GPL also, but it is not clear to me. Please clarify.

**Comment by hawkchen** [comment]
The license of ZK CE doesn't contain ZK Spreadsheet. They are separate. ZK Spreadsheet is a different product which bases on ZK framework, and you need to buy a license for using ZK Spreadsheet.

ZK CE is free, but PE and EE requires a license.

**Comment by Hubbitus** [comment]
Thank you for the answer.
