### ISSUE TITLE
build file is a little difficult to use

### ISSUE THREAD

**Issue by zhangshengshan** [zkoss/zkspreadsheet#110]

**Comment by zhangshengshan** [comment]
I mean there should be a README.md or something like that which could show how to compile the whole project step by step

**Comment by uptonking** [comment]
build from source failed.

```
cd zkspreadsheet
./build 
```
 there comes problem one by one

```
 D.ON=trueild.setting must be either true or false -- not true  
ZSSCML path is not found!!
ZSSPOI path is not found!!
Illegal setting: debug=true
````

**Comment by hawkchen** [comment]
Thanks for trying, but we currently expect to build zss internally.
